version: "3.1"
services:
  back_leche-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: back_leche_App_container
    # image: a7medabdo6/care_managment
    volumes:
      - ./src:/back_leche_App/src:ro
    ports:
      - "7050:7050"