version: "3.1"
services:
  back_leche-app:
    build:
      context: ./back_leche
      dockerfile: Dockerfile
    container_name: back_leche_app_container
    # image: a7medabdo6/care_managment
    volumes:
      - ./back_leche/src:/back_leche_App/src:ro
    ports:
      - "7050:7050"
  react:
    build:
      context: ./leche
      dockerfile: Dockerfile
    container_name: React_leche_container
    volumes:
      - ./leche/src:/React_leche/src:ro
    ports:
      - "3060:3060"
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    build:
       context: ./
       dockerfile: Dockerfile.nginx
    ports:
       - 86:86
    restart: always
