version: "3.1"
services:
  leche-app:
    build:
      context: ./back_leche
      dockerfile: Dockerfile
    container_name: back_leche_container
    volumes:
      - ./back_leche/src:/back_leche_app/src:ro
    ports:
      - "7050:7050"
  react:
    build:
      context: ./leche
      dockerfile: Dockerfile
    container_name: React_leche_container
    volumes:
      - ./namshy_frontend/src:/React_leche/src:ro
    ports:
      - "3060:3060"
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    ports:
      - 86:80
    restart: always
