version: "3.1"
services:
  react:
    build:
      context: ./leche
      dockerfile: Dockerfile
    container_name: React_leche_container
    volumes:
      - ./leche/src:/React_leche/src:ro
    ports:
      - "3060:3060"
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    # volumes:
    #     - ./Care_Frontend/build:/usr/share/nginx/html:ro
    ports:
      - 89:80
    restart: always
